
(()=>{
const root=document.getElementById('tmrw-home-demo'),q=id=>root.querySelector('#tmrw-'+id),calendar=root.querySelector('.calendar'),sheet=q('sheet'),content=q('sheet-content');
const months=['january','february','march','april','may','june','july','august','september','october','november','december'],weekdays=['sunday','monday','tuesday','wednesday','thursday','friday','saturday'];
let year=2026,month=8,selected='',origin=null,busy=false,opened=false,oldHeight='';const entries=new Map(),reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
const shades=['#404040','#666666','#919191','#bcbcbc','#ffffff'];
const blank=()=>({yesterday:Array.from({length:3},()=>({text:'',done:false})),tomorrow:Array.from({length:3},()=>({text:'',done:false})),today:'',rating:0});
const markers=Array.from(root.querySelectorAll('.marker'));
function paintRating(value){markers.forEach((m,i)=>{m.style.background=i<value?shades[i]:'#000';m.setAttribute('aria-pressed',String(data().rating===i+1));m.setAttribute('aria-label','Rating '+(i+1)+' of 5')})}
function paintDay(b,rating){b.style.setProperty('--day-shade',rating?shades[rating-1]:'#000');b.style.color=rating>=3?'#000':'#fff';b.setAttribute('aria-label',months[month]+' '+b.dataset.day+', '+year+(rating?', rating '+rating+' of 5':''))}
function data(){return entries.get(selected)}
let user=null, mode='login', loading=true;
const dirty=new Set(), blocked=new Set();let flushing=false, timer;
const accountForm=document.getElementById('account-form');
const message=document.getElementById('account-message');
async function api(path,method='GET',body){const response=await fetch('/api/'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-Tmrw':'1'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok){const e=new Error(result.error||'Could not save. Please try again.');e.status=response.status;throw e}return result}
function storageMessage(){document.getElementById('account-title').textContent=user?'user #'+user:'your space.';accountForm.hidden=!!user;document.getElementById('account-signed').hidden=!user;document.getElementById('account-number').textContent=user?'Your login number is #'+user+'.':''}
function setMode(next){mode=next;document.getElementById('user-label').hidden=mode==='create';document.getElementById('confirm-label').hidden=mode!=='create';accountForm.elements.confirm.required=mode==='create';accountForm.elements.password.autocomplete=mode==='create'?'new-password':'current-password';document.getElementById('account-submit').textContent=mode==='create'?'create profile':'log in';message.textContent='';}
document.getElementById('mode-login').onclick=()=>setMode('login');document.getElementById('mode-create').onclick=()=>setMode('create');
function status(text){q('status').classList.remove('sr');q('status').textContent=text}
function save(){if(!user)return;dirty.add(selected);status('saving…');clearTimeout(timer);timer=setTimeout(flush,450)}
async function flush(){if(flushing)return false;flushing=true;let ok=true;try{for(const key of [...dirty]){if(blocked.has(key)){ok=false;continue}dirty.delete(key);const entry=entries.get(key);const payload=JSON.parse(JSON.stringify(entry));payload.version=entry.version||0;try{const result=await api('entries/'+key,'PUT',payload);entry.version=result.version}catch(e){dirty.add(key);if(e.status===409)blocked.add(key);status(e.message);ok=false;break}}if(ok&&!dirty.size)status('saved');}finally{flushing=false}if(ok&&dirty.size&&!blocked.size)timer=setTimeout(flush,450);return ok&&!dirty.size}
async function loadEntries(){const result=await api('entries');entries.clear();for(const [key,value] of Object.entries(result.entries))entries.set(key,value);render()}
accountForm.onsubmit=async e=>{e.preventDefault();const submit=document.getElementById('account-submit');if(mode==='create'&&accountForm.elements.password.value!==accountForm.elements.confirm.value){message.textContent='Passwords do not match.';return}submit.disabled=true;message.textContent='';try{const result=await api(mode==='create'?'register':'login','POST',{user:accountForm.elements.user.value.trim(),password:accountForm.elements.password.value});user=result.user;accountForm.reset();await loadEntries();storageMessage();message.textContent='You are user #'+user+'.';status('saved');}catch(e){message.textContent=e.message}finally{submit.disabled=false}};
document.getElementById('account-logout').onclick=async()=>{if(dirty.size&&!await flush()){message.textContent='Save has not finished. Keep this page open and retry before logging out.';return}try{if(opened)await closeDay();await api('logout','POST',{});user=null;entries.clear();dirty.clear();blocked.clear();render();storageMessage();status('');message.textContent='Logged out.'}catch(e){message.textContent=e.message}};
window.addEventListener('beforeunload',e=>{if(dirty.size){e.preventDefault();e.returnValue=''}});
window.addEventListener('online',()=>{if(dirty.size)flush()});
window.addEventListener('focus',async()=>{if(user&&!opened&&!dirty.size&&!flushing){try{await loadEntries()}catch(e){status(e.message)}}});
async function initialize(){try{const result=await api('me');user=result.user;if(user)await loadEntries();else{q('profile-panel').hidden=false;q('profile').setAttribute('aria-expanded','true')}}catch(e){message.textContent='Could not connect to the server. Reload to retry.'}finally{loading=false;storageMessage()}}
initialize();
function previousKey(key){const [y,m,d]=key.split('-').map(Number);const prev=new Date(y,m,d-1);return prev.getFullYear()+'-'+prev.getMonth()+'-'+prev.getDate()}
function linkedYesterday(){const prior=entries.get(previousKey(selected));return Array.from({length:3},(_,i)=>{const text=prior?.tomorrow[i]?.text||'';let task=data().yesterday[i];if(!task||task.text!==text)task=data().yesterday[i]={text,done:false};return task})}
function tasks(group){q(group).replaceChildren();const list=group==='yesterday'?linkedYesterday():data().tomorrow;list.forEach((task,i)=>{const row=document.createElement('div');row.className='task-row';const c=document.createElement('input');c.type='checkbox';c.className='cursor-interaction';c.checked=task.done;c.setAttribute('aria-label',(group==='yesterday'?'From yesterday':'For tomorrow')+' task '+(i+1)+' completed');c.onchange=()=>{task.done=c.checked;save()};const t=document.createElement('input');t.type='text';t.maxLength=200;t.value=task.text;t.readOnly=group==='yesterday';t.setAttribute('aria-label',(group==='yesterday'?'From yesterday':'For tomorrow')+' task '+(i+1));t.oninput=()=>{task.text=t.value;save()};row.append(c,t);q(group).append(row)})}
const ordinal=d=>(d%100>=11&&d%100<=13)?'th':({1:'st',2:'nd',3:'rd'}[d%10]||'th');
function geometry(el){const a=el.getBoundingClientRect(),r=root.getBoundingClientRect();return {left:(a.left-r.left)+'px',top:(a.top-r.top)+'px',width:a.width+'px',height:a.height+'px'}}
async function animate(frames,closing){if(reduced.matches)return;const a=sheet.animate(frames,{duration:closing?440:590,easing:'cubic-bezier(.22,1,.36,1)',fill:'none'});await a.finished.catch(()=>{})}
async function openDay(b,d){if(busy||opened||loading)return;if(!user){q('profile-panel').hidden=false;q('profile').setAttribute('aria-expanded','true');return}busy=true;origin=b;selected=year+'-'+month+'-'+d;if(!entries.has(selected))entries.set(selected,blank());const from=geometry(b);closeMenus();q('day-title').textContent=weekdays[new Date(year,month,d).getDay()]+', '+months[month]+' '+d+ordinal(d);tasks('yesterday');tasks('tomorrow');q('today').value=data().today;paintRating(data().rating);oldHeight=root.style.minHeight;root.style.minHeight=(window.innerWidth<650?815:850)+'px';sheet.hidden=false;content.style.opacity='0';const to=geometry(sheet);root.classList.add('expanded');calendar.inert=true;opened=true;await animate([{...from,background:'#333',borderColor:'#999'},{...to,background:'#000',borderColor:'#fff'}],false);content.style.opacity='1';if(!reduced.matches)content.animate([{opacity:0,transform:'translateY(6px)'},{opacity:1,transform:'translateY(0)'}],{duration:180,easing:'ease-out'});busy=false;q('close').focus({preventScroll:true})}
async function closeDay(){if(busy||!opened)return;if(dirty.size)flush();busy=true;const from=geometry(sheet),to=geometry(origin);content.style.opacity='0';root.classList.remove('expanded');origin.style.visibility='hidden';await animate([{...from,background:'#000'},{...to,background:data().rating?shades[data().rating-1]:'#000'}],true);sheet.hidden=true;origin.style.visibility='';root.style.minHeight=oldHeight;calendar.inert=false;opened=false;busy=false;origin.focus({preventScroll:true})}
function render(){q('month').textContent=months[month];q('year').textContent=year;q('days').setAttribute('aria-label',months[month]+' '+year+' calendar');q('days').replaceChildren();for(let n=0;n<new Date(year,month,1).getDay();n++){const b=document.createElement('div');b.setAttribute('aria-hidden','true');q('days').append(b)}for(let d=1;d<=new Date(year,month+1,0).getDate();d++){const b=document.createElement('button');b.type='button';b.className='day cursor-interaction';b.dataset.day=d;paintDay(b,entries.get(year+'-'+month+'-'+d)?.rating||0);b.setAttribute('aria-label',months[month]+' '+d+', '+year);const s=document.createElement('span');s.className='number';s.textContent=d;b.append(s);b.onclick=()=>openDay(b,d);paintDay(b,entries.get(year+'-'+month+'-'+d)?.rating||0);q('days').append(b)}}
function closeMenus(){['menu','profile'].forEach(id=>{q(id+'-panel').hidden=true;q(id).setAttribute('aria-expanded','false')})}
['menu','profile'].forEach(id=>q(id).onclick=()=>{const open=q(id+'-panel').hidden;closeMenus();q(id+'-panel').hidden=!open;q(id).setAttribute('aria-expanded',String(open))});
root.querySelectorAll('[data-month]').forEach(b=>b.onclick=async()=>{if(busy)return;if(opened)await closeDay();const next=new Date(year,month+Number(b.dataset.month),1);year=next.getFullYear();month=next.getMonth();render()});
q('dates').onchange=e=>root.classList.toggle('show-dates',e.target.checked);q('close').onclick=closeDay;q('today').oninput=e=>{data().today=e.target.value;save()};markers.forEach((m,i)=>{m.onpointerenter=()=>paintRating(i+1);m.onfocus=()=>paintRating(i+1);m.onclick=()=>{data().rating=i+1;paintRating(data().rating);paintDay(origin,data().rating);save()}});root.querySelector('.markers').onpointerleave=()=>paintRating(data().rating);root.querySelector('.markers').onfocusout=e=>{if(!e.currentTarget.contains(e.relatedTarget))paintRating(data().rating)};root.addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenus();closeDay()}});storageMessage();render();
})();
